const phraseElement = document.getElementById("phrase")

// Random pop-culture references/book quotes/song lyrics/thoughts
const phrases = [
  "into the blue again, after the money's gone",
  "sometimes the instruments have more to say than the artist", 
  "mi lon tomo",
  "finger's on the trigger of a money game",
  "... because there's some interesting philosophy here",
  "we'll be fine because of trickle down economics",
  "I hope someday Selmers rides her fuckin' train",
  "what's left unsaid is that ... [AI/AGI] can be whatever OpenAI wants.",
  "under pressure",
  "why don't we keep it coming back and coming back and coming back and coming back",
  "hey! you! feed the machine! bring them up back down to their knees!",
  "we're an anarcho-syndicalist commune",
  "futures made of virtual insanity",
  "i use arch btw",
  "you should be using Signal",
  "imagine no possessions. I wonder if you can?",
  "how to blow up a pipeline",
  "can there be a good dictator?",
  "Valerie",
  "don't wanna be an American idiot",
  "invest in gold",
  "I don't wanna die, I sometimes wish I'd never been born at all",
  "free Gaza",
  "people dying is bad actually",
  "I'd love it if we made it",
  "strike or die",
  "this site is monolingual",
  "this site doesn't support IE7",
  "#1 AI hater",
  "#1 dying hater (we should stop doing that)",
  "consumer rights",
  "people hyped up Kanye so much and he made good music but he said exactly 0 things I care about",
  "it's such a beautiful day",
  "",
  "but we're going to die some day",
  "save the world",
  "let it happen",
  "free Luigi",
  "am I a hypocrit?",
  "also try: the fediverse",
  "I never believed Elon Musk was a Nazi, because that's too optimistic",
  "Palantir is bad actually",
  "fight chat control",
  "</clippy>",
  "approach every task with the skill that Freddie Mercury used to approach his craft.",
  "*it* won't happen any time soon",
  "healthcare is a human right",
  "housing is a human right",
  "not starving is a human right",
  "Elon Musk: who could've ended world hunger but didn't",
  "vote for Zohran Mamdani",
  "the NDP should try harder",
  "mi toki e toki pona",
  "je parle français*",
  "also see: https://www.dementiaman.com"
]
phraseElement.innerText = `"${phrases[Math.floor(Math.random() * phrases.length)]}"`
